### ISSUE TITLE
Zet deze array in een andere file

### ISSUE THREAD

**Issue by samclarkb** [thimogagliano/Project-Tech-22-23#8]
Zet deze array in een andere file, zodat je app.js een niet te lange file wordt.

https://github.com/thimogagliano/Project-Tech-22-23/blob/6937f59a0c1914771d1b8b4524e0de8b8ec38127/server.js#L8-L34

**Comment by thimogagliano** [comment]
Heb ik gedaan, bedankt voor de issue
