### ISSUE TITLE
Inlcude the HTML en de Body tag in je head.ejs

### ISSUE THREAD

**Issue by samclarkb** [thimogagliano/Project-Tech-22-23#9]
Inlcude the HTML en de Body tag in je head.ejs, zodat je die tags niet telkens op iedere pagina moet aanmaken.

https://github.com/thimogagliano/Project-Tech-22-23/blob/2e044121b54793aa524d935f0eb3682ec7028695/views/partials/head.ejs#L1-L5

**Comment by thimogagliano** [comment]
Bedankt voor de issue
